### ISSUE TITLE
Hi, do I have to enable https to use brotli?

### ISSUE THREAD

**Issue by himonster1** [georg-jung/nginx-brotli#2]
Hi, do I have to enable https to use brotli?

**Comment by georg-jung** [comment]
Yes.

Google's first result for  "brotli https": https://stackoverflow.com/a/43862563

> The reason to limit brotli to secure contexts is that intermediaries (specifically, buggy proxies and content scanners) tend to behave very poorly when they encounter non-deflate/gzip Content-Encoding. The Google guys discovered this when they rolled out ‘sdch’ and ‘bzip2’ before that; they ended up pulling bzip2 partly for that reason and sdch has a number of hacks that they had to put in. By requiring HTTPS for brotli, they can head off this problem in most cases because comparatively few content-scanners MITM HTTPS streams

**Comment by himonster1** [comment]
thanks
