### ISSUE TITLE
hi,Is it possible to provide Dockerfile files? I would like to learn it, thanks!

### ISSUE THREAD

**Issue by ezrawic4j** [georg-jung/nginx-brotli#3]

**Comment by georg-jung** [comment]
Sure, everything about this project is fully open source and already publicly available. This repo does not make use of any Dockerfile I created though. The Dockerfile is created, maintained and hosted by NGINX, Inc. and available here: <https://github.com/nginxinc/docker-nginx/tree/master/modules>

This repo automates building the docker image using the Github Actions workflow in [build.yml](https://github.com/georg-jung/nginx-brotli/blob/master/.github/workflows/build.yml). Automatic rebuilding on a cron-schedule is achieved using [cron-docker-rebuild.yml](https://github.com/georg-jung/nginx-brotli/blob/master/.github/workflows/cron-docker-rebuild.yml), which uses <https://github.com/georg-jung/docker-image-update-checker>.

**Comment by georg-jung** [comment]
Feel free to reopen/ask any further questions if you have some.
