### ISSUE TITLE
arm64 images please!

### ISSUE THREAD

**Issue by rsubr** [georg-jung/nginx-brotli#4]
Thanks for the great project. I'm using brotli static to serve large files very effectively.

Many cloud providers are offering `arm64` VMs which are significantly lower in cost compared to `amd64`. Static file serving is well suited for small/cheap servers.

Can you pls update the container build process to create native `linux/arm64` docker images?

Thanks again.

**Comment by georg-jung** [comment]
Sorry for the long response time. arm64 images should be available now. Would be great to hear some feedback on them.

**Comment by marvinruder** [comment]
@georg-jung I deployed the image on two Hetzner Cloud Servers with arm64 architecture and activated Brotli compression – everything works as expected. Thanks for your work!

**Comment by georg-jung** [comment]
Great to hear, thanks!
